Week 1. Create models
Dev-incubator/DIMS-Core.Double-4 pull request #1
Opened 2021-06-29 06:30 UTC by dzmitri-litvinov

2021-06-29 09:10 UTC, UNDogMan requested changes
Also clean your code.

2021-06-29 09:10 UTC, UNDogMan commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserTasks.sql
> +    FOREIGN KEY (StateId) REFERENCES TaskStates (StateId)
Foreign keys also shoud be named.

2021-06-29 09:10 UTC, UNDogMan commented on DIMS-Core.Database/DIMS-Core.Database/Views/vTasks.sql
> +FROM [Tasks]
Explicitly specify fields for views.

2021-06-30 16:54 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskTracks.sql
> +	FOREIGN KEY (UserTaskId) REFERENCES UserTasks (UserTaskId)
OMG could you use formatting? It is confused me....
Or don't use it. But Don't try to align it by your own.

2021-06-30 16:54 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskTracks.sql
> +    [TrackNote]			NVARCHAR(250)	NULL,
These field cannot be null because it doesn't make seanse. User can create track note without date and note... Why?

2021-06-30 16:54 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Tables/Tasks.sql
> +
Start and end date cannot be null

2021-06-30 16:54 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Views/vTasks.sql
> +FROM [Tasks]
Agree, specify all fields

2021-06-30 16:59 UTC, PushMeNow requested changes

2021-06-30 16:59 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Models/DIMSCoreContext.cs
> +            }
Remove it. You already have it in startup class

2021-07-01 10:06 UTC, dzmitri-litvinov commented on DIMS-Core/DIMS-Core.DataAccessLayer/Models/DIMSCoreContext.cs
> +            }
Removed

2021-07-01 10:34 UTC, dzmitri-litvinov commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskTracks.sql
> +	FOREIGN KEY (UserTaskId) REFERENCES UserTasks (UserTaskId)
Done

2021-07-01 10:47 UTC, dzmitri-litvinov commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserTasks.sql
> +    FOREIGN KEY (StateId) REFERENCES TaskStates (StateId)
Done in all the tables

2021-07-01 10:54 UTC, dzmitri-litvinov commented on DIMS-Core.Database/DIMS-Core.Database/Views/vTasks.sql
> +FROM [Tasks]
![image](https://user-images.githubusercontent.com/79978383/124113222-dab01880-da73-11eb-8c1e-27e57094b16d.png)
Done

2021-07-01 10:58 UTC, dzmitri-litvinov commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskTracks.sql
> +    [TrackNote]			NVARCHAR(250)	NULL,
Agree
![image](https://user-images.githubusercontent.com/79978383/124113660-5ad67e00-da74-11eb-8be4-d2b0bf80e825.png)

2021-07-01 10:59 UTC, dzmitri-litvinov commented on DIMS-Core.Database/DIMS-Core.Database/Tables/Tasks.sql
> +
![image](https://user-images.githubusercontent.com/79978383/124113769-7cd00080-da74-11eb-8f25-034e1aa47792.png)
Agree

2021-07-02 07:58 UTC, PushMeNow requested changes

2021-07-02 07:58 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/DIMS-Core.Database.sqlproj
> +    <OutputPath>D:\DevInc\DIMS\DB\</OutputPath>
return this back

2021-07-02 07:58 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/DirectionService.cs
> +using AliasThreading = System.Threading.Tasks;
hm... I told about alias for class but you did for namespace. It is useless because you still use namespace to call Task class. Use alias for class.

2021-07-02 11:04 UTC, dzmitri-litvinov commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/DirectionService.cs
> +using AliasThreading = System.Threading.Tasks;
![image](https://user-images.githubusercontent.com/79978383/124264929-c3d5f880-db3d-11eb-920e-9f784ebb81f4.png)
Done in `UnitOfWork`, `IUnitOfWork` and `DirectionRepositoryTest`.
![image](https://user-images.githubusercontent.com/79978383/124265208-13b4bf80-db3e-11eb-8bbf-49a950228ed7.png)
But not done in `DirectionService` and `UserProfileService` as `using aliases` can name a closed constructed type, but cannot name an unbound generic type declaration without supplying type arguments.
Shall I create the bunded generic types for each case or shall I leave it as it is?

2021-07-02 11:13 UTC, dzmitri-litvinov commented on DIMS-Core.Database/DIMS-Core.Database/DIMS-Core.Database.sqlproj
> +    <OutputPath>D:\DevInc\DIMS\DB\</OutputPath>
![image](https://user-images.githubusercontent.com/79978383/124266407-9e49ee80-db3f-11eb-997c-8e6a2b1bc770.png)
Done

2021-07-03 07:28 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/DirectionService.cs
> +using AliasThreading = System.Threading.Tasks;
Well in this case use alias for Task entity

2021-07-05 07:35 UTC, dzmitri-litvinov commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/DirectionService.cs
> +using AliasThreading = System.Threading.Tasks;
![image](https://user-images.githubusercontent.com/79978383/124434573-b2c6fa80-dd7c-11eb-8eea-93e149ddb148.png)
Done

2021-07-05 17:23 UTC, PushMeNow approved these changes

2021-07-05 17:23 UTC, merged